# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhxsx7xNcmZNf1KfwqOkLmZ1pALi0TRH
"""

import pandas as pd
import numpy as np
import json

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split

df = pd.read_csv("oil_retail_history.csv")

# Make sure date is datetime (IMPORTANT)
df["date"] = pd.to_datetime(df["date"])

# Remove bad rows
df = df[df["volume"] >= 0]
df = df[df["price"] >= df["cost"]]
df = df.dropna()

# Sort by date
df = df.sort_values("date")

df

# Competitor features
df["comp_avg"] = (df["comp1_price"] + df["comp2_price"] + df["comp3_price"]) / 3
df["price_vs_comp"] = df["price"] - df["comp_avg"]

# Lag features
df["price_lag_1"] = df["price"].shift(1)
df["volume_lag_1"] = df["volume"].shift(1)
df["volume_lag_7"] = df["volume"].shift(7)

# Rolling features
df["rolling_vol_7"] = df["volume"].rolling(7).mean()
df["rolling_price_7"] = df["price"].rolling(7).mean()

# Time features
df["day_of_week"] = df["date"].dt.weekday
df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)
df["month"] = df["date"].dt.month

# Drop rows created by lagging
df = df.dropna()

df

features = [
    "price", "cost",
    "comp1_price", "comp2_price", "comp3_price",
    "price_vs_comp",
    "price_lag_1",
    "volume_lag_1", "volume_lag_7",
    "rolling_vol_7", "rolling_price_7",
    "is_weekend", "month"
]

x = df[features]
y = df["volume"]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,shuffle=False)

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

rf.fit(x_train, y_train)

pred = rf.predict(x_test)
mape = mean_absolute_percentage_error(y_test, pred)

print("Validation MAPE:", round(mape * 100, 2), "%")

with open("today_example.json") as f:
    today = json.load(f)

today_date = pd.to_datetime(today["date"])

today_date

# Competitor features
today_comp_avg = (
    today["comp1_price"] +
    today["comp2_price"] +
    today["comp3_price"]
) / 3

# Last known values from history
last_row = df.iloc[-1]

today_row = {
    "price": today["price"],
    "cost": today["cost"],
    "comp1_price": today["comp1_price"],
    "comp2_price": today["comp2_price"],
    "comp3_price": today["comp3_price"],
    "price_vs_comp": today["price"] - today_comp_avg,
    "price_lag_1": last_row["price"],
    "volume_lag_1": last_row["volume"],
    "volume_lag_7": last_row["volume_lag_7"],
    "rolling_vol_7": last_row["rolling_vol_7"],
    "rolling_price_7": last_row["rolling_price_7"],
    "is_weekend": today_date.weekday() in [5, 6],
    "month": today_date.month
}

best_price = None
best_profit = -1

# Price range (±3%)
min_price = max(today["cost"] * 1.02, today["price"] * 0.97)
max_price = today["price"] * 1.03

for price in np.linspace(min_price, max_price, 20):
    today_row["price"] = price

    X_today = pd.DataFrame([today_row])[features]
    volume = rf.predict(X_today)[0]

    profit = (price - today["cost"]) * volume

    if profit > best_profit:
        best_profit = profit
        best_price = price
        best_volume = volume

print("Recommended Price:", round(best_price, 2))
print("Expected Volume:", int(best_volume))
print("Expected Profit:", int(best_profit))

